---
- name: Install common packages | makes for nicer admin/user experience later
  apt: name=$item state=present update_cache=yes
  with_items:
    - python-software-properties
    - python-pip
    - python-setuptools
    - python-mysqldb
    - python-psycopg2
    - etckeeper
    - git

- name: Install ${openstack_release} repo
  apt_repository: repo=ppa:openstack-ubuntu-testing/${openstack_release}-testing
  only_if: is_set('$openstack_release')
